version: '3.9'
services:
  client-frontend:
    image: front:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true # для открытия терминала после старта