version: '3.9'
services:
  client-backend:
    #    2 цифра - для общего, 3 для частности
    image: client:0.1.0
    build:
      context: ./backend-chat
      dockerfile: Dockerfile
    #      указываем расположение Dockerfile
    ports:
      - "8080:8080"
#     внешний:внутренний
    depends_on:
      - zookeeper-1
      - kafka-1

  #  client-frontend:
  #    image: front:0.0.5
  #    build:
  #      context: /frontend-chat
  #      dockerfile: Dockerfile
  #    ports:
  #      - '3000:3000'
  #    stdin_open: true
  #    tty: true # для открытия терминала после ст
  #    depends_on:
  #      - client-backend
  #

